---

- hosts: nginx
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles: 
    - dnsmasq
#    - superusers
#    - nginx-php-fpm
  vars_files:
    - vars/default.yml
